apiVersion: v1
kind: Service
metadata:
  name: backend-demo-app-service
spec:
  selector:
    app: backend-demo-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
